INSERT INTO roles (id, name) VALUES
(1, 'ROLE_ADMIN')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(2, 'ROLE_USER')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(3, 'ROLE_MANAGER')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(4, 'ROLE_EMPLOYEE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(5, 'ROLE_PENDING_EMPLOYEE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(6, 'ROLE_CANDIDATE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles (id, name) VALUES
(7, 'ROLE_GUEST')
ON CONFLICT (id) DO NOTHING;
